### ISSUE TITLE
Tumblr returns 'oauth_signature does not match expected value' on requesting a token

### ISSUE THREAD

**Issue by binarte** [sirikata/liboauthcpp#22]
Trying to authenticate to tumblr, it refuses to return a request tokenclaiming a wrong signature, and I've used the built-in demo to try it with 2 different app key/secrets already

Edit: flickr seems to give the same error

**Comment by ewencp** [comment]
My bad for not following up. From what I've seen previously, frequently this has to do with timestamps/time synchronization. The library definitely works with some other sites, such as twitter, but it's possible other issues besides timing could arise. Encoding issues or special characters come to mind.

Since this is old, I'm going to comment & close, but if you want to follow up and have more info (logs, request info with sensitive info removed, etc), please reopen an we can follow up.
